version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_status
        tests:
          - accepted_values:
              arguments:
                values: ['active', 'inactive', 'blocked']

  - name: stg_categories
    columns:
      - name: category_id
        tests:
          - unique
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: category_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_categories')
                field: category_id

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id
      - name: order_status
        tests:
          - accepted_values:
              arguments:
                values: ['pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned']

  - name: stg_order_items
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
      - name: payment_status
        tests:
          - accepted_values:
              arguments:
                values: ['paid', 'failed', 'pending', 'refunded']

  - name: stg_shipments
    columns:
      - name: shipment_id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id
      - name: shipment_status
        tests:
          - accepted_values:
              arguments:
                values: ['delivered', 'in_transit', 'returned']

  - name: stg_reviews
    columns:
      - name: review_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id
      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id
