name: 'ecommerce_dbt'
version: '1.0.0'
profile: 'ecommerce_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_dbt:
    raw:
      +materialized: view
    staging:
      +materialized: view
    marts:
      dim:
        +materialized: table
      fct:
        +materialized: incremental
      agg:
        +materialized: table

seeds:
  ecommerce_dbt:
    +quote_columns: false
